const ActionTypes = {
	GET_TODO_LIST: 'GET_TODO_LIST',
	TODO_LIST_SUCCESS: 'TODO_LIST_SUCCESS',
	TODO_LIST_FAIURE: 'TODO_LIST_FAIURE',
	CREATE_TODO_ITEM: 'CREATE_TODO_ITEM',
	CREATE_TODO_ITEM_SUCCESS: 'CREATE_TODO_ITEM_SUCCESS',
	CREATE_TODO_ITEM_FAILURE: 'CREATE_TODO_ITEM_FAILURE',
	UPDATE_TODO_ITEM: 'UPDATE_TODO_ITEM',
	UPDATE_TODO_ITEM_FAILURE: 'UPDATE_TODO_ITEM_FAILURE',
	UPDATE_TODO_ITEM_SUCCESS: 'UPDATE_TODO_ITEM_SUCCESS',
	DELETE_TODO_ITEM: 'DELETE_TODO_ITEM',
	DELETE_TODO_ITEM_FAILURE: 'DELETE_TODO_ITEM_FAILURE',
	DELETE_TODO_ITEM_SUCCESS: 'DELETE_TODO_ITEM_SUCCESS',
	
}

export default ActionTypes